import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import kaamelott from "@/pages/api/kaamelott"; 
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [quote, setQuote] = useState("");
  const [character, setCharacter] = useState("");

  async function fetchQuote() {
    const api = await fetch('/api/kaamelott');
    const data = await api.json();
    
    setQuote(data.citation.citation)
    setCharacter(data.citation.infos.personnage)
  }

  useEffect (()=> {
    fetchQuote();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.quote}>
        <h1>{character}</h1>
         <h2>{quote}</h2>
          <button className={styles.btn} onClick={fetchQuote}>Nouvelle citation</button>
        </div>
      </main>
    </>
  );
}
